### ISSUE TITLE
Start the daemon with AmuleWebUI-Reloaded

### ISSUE THREAD

**Issue by agusgambina** [MatteoRagni/AmuleWebUI-Reloaded#11]
First of all thank you for your work, I really appreciate it. I can't make the service (I mean when I boot the computer) start with AmuleWebUI-Reloaded always start with the default theme and I have to run 

```
$ kill $(pidof amuleweb) && amuleweb
```

to make it work.

I think I am making a mistake in the configuration files or something like that. In my ``amule.conf``

```
[WebServer]
Enabled=1
Password=####
PasswordLow=
Port=4711
WebUPnPTCPPort=50001
UPnPWebServerEnabled=0
UseGzip=1
UseLowRightsUser=0
PageRefreshTime=120
Template=
Path=amuleweb
```

If I put the Template field the theme in ``amule.conf`` the service start with the theme but seems not to have any configuration.

and in my ``remote.conf``

```
Locale=
[EC]
Host=localhost
Port=4712
Password=####
[Webserver]
Port=4711
UPnPWebServerEnabled=1
UPnPTCPPort=50001
Template=AmuleWebUI-Reloaded
UseGzip=0
AllowGuest=0
AdminPassword=####
GuestPassword=
```

Thank you

**Comment by MatteoRagni** [comment]
Maybe it is started with an UID different than yours, and loads a configuration placed in another HOME?

**Comment by agusgambina** [comment]
I am not sure what happened, but I reinstalled ubuntu (for other reasons) and in the amule.conf in the [WebServer] file I changed

    Template=AmuleWebUI-Reloaded

and worked perfectly, but I am not sure what it was.
