### ISSUE TITLE
Sort by "sources" in amuleweb-main-search.php

### ISSUE THREAD

**Issue by gise88** [MatteoRagni/AmuleWebUI-Reloaded#12]
I have noticed this bug and I have already fixed it by changing the following line:
`<th><a href="amuleweb-main-search.php?sort=srccount">Sources</a></th>` 
with this one:
`<th><a href="amuleweb-main-search.php?sort=sources">Sources</a></th>`

Thank you for this great repo!! :)

**Comment by MatteoRagni** [comment]
Please, fork the repo, do the modification and issue a pull request, so your username will be connected to corrections!

Thank you!
