### ISSUE TITLE
Reloaded style

### ISSUE THREAD

**Issue by jjmeseguerrr** [MatteoRagni/AmuleWebUI-Reloaded#20]
Hi,
Is there a way to use the Reloaded style instead of the Reloaded Material style?
Thanks!

**Comment by MatteoRagni** [comment]
The fastest way is by cloning and checking out to commit `7ab1b03`... Or you download the zip from this page (https://github.com/MatteoRagni/AmuleWebUI-Reloaded/tree/7ab1b03e2521aa3c54ab7f9c3b25a9af8cc3deb4)
