### ISSUE TITLE
Different font type in the header section

### ISSUE THREAD

**Issue by garret** [MatteoRagni/AmuleWebUI-Reloaded#21]
I cannot understand why the font type in the interface is quite different from the screens in the readme GitHub page. This is how I see the interface: 
![image](https://user-images.githubusercontent.com/27555/105179704-eba24880-5b29-11eb-97d7-d5f280323f7f.png)

As you can notice, the header section uses a serif font (like Times New Roman) whereas on the GitHub page the interface looks nicer with sans serif fonts (example below). I have the above result either with Firefox/Chrome on both Windows and Linux. 
![image](https://user-images.githubusercontent.com/27555/105179748-fb219180-5b29-11eb-8551-6c1728fb2ba8.png)

Do you know how to achieve the same result as in the GitHub screenshots?

**Comment by tetreum** [comment]
@MatteoRagni this issue can be closed too :)

**Comment by garret** [comment]
I close it, even though I still have to try it. But I just trust :)
