### ISSUE TITLE
Show complete file name

### ISSUE THREAD

**Issue by ngosang** [MatteoRagni/AmuleWebUI-Reloaded#25]
I have several files with long names. Some of them have the same name but the last part.
In shared and transfers windows I can't see the full name.

![image](https://user-images.githubusercontent.com/10577978/114285140-0911ef00-9a55-11eb-8571-2c6e45945f83.png)

Could you show the full name in the tooltip/title?

**Comment by MatteoRagni** [comment]
I think the merge made by @mercu01 tackles this issue. I'm closing it for now, feel free to comment if that is not true.

**Comment by ngosang** [comment]
@MatteoRagni I just tested that PR and it's not fixed. In my desktop it looks perfect because my screen is big, the issue is in my mobile. I would like to have a tooltip with the complete name when I hover the cursor/finger.
Maybe @mercu01 can implement it => https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_global_title

**Comment by ngosang** [comment]
Go for it
