### ISSUE TITLE
Total size is wrong when the list of torrents is empty

### ISSUE THREAD

**Issue by ngosang** [MatteoRagni/AmuleWebUI-Reloaded#32]
Total size is wrong when the list of torrents is empty. It also looks weird. This is the first thing the user see when it installs aMule. Maybe we should add the word "Total" in the filename column or something like that.

Caused by #28
@mercu01 could you take a look?

![image](https://user-images.githubusercontent.com/10577978/191071024-e886c401-2802-42c8-835e-c120da6c6dcd.png)

**Comment by mercu01** [comment]
Sorry friend, I should have tried it :/
I open pr to fix #33 and add tag "total"
